workflows:
  android-build:
    name: Android Build
    max_build_duration: 120
    environment:
      flutter: 3.22.0 # A recent stable version that should include a compatible Dart SDK
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Set up Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Build Android Release
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com # Replace with your email to receive build notifications
        notify:
          success: true
          failure: true

